# Generated by Django 6.0.6 on 2026-06-10 14:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='出生地')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱')),
            ],
            options={
                'verbose_name': '作者详情',
                'verbose_name_plural': '作者详情',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#6c5ce7', max_length=7, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='O', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='国籍')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.authorprofile', verbose_name='作者详情')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('isbn', models.CharField(blank=True, max_length=13, unique=True, verbose_name='ISBN号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='价格')),
                ('pages', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='页数')),
                ('publication_date', models.DateField(default=datetime.date.today, verbose_name='出版日期')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='畅销书')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='有库存')),
                ('language', models.CharField(choices=[('ZH', '中文'), ('EN', '英文'), ('JA', '日文'), ('OT', '其他')], default='ZH', max_length=2, verbose_name='语言')),
                ('description', models.TextField(blank=True, verbose_name='图书简介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图片')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.author', verbose_name='作者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='books.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-publication_date'],
            },
        ),
    ]
